### ISSUE TITLE
Support Elixir 1.6

### ISSUE THREAD

**Issue by yjchen** [nroi/paracusia#5]
The latest paracusia (0.2.7) requires Elixir 1.7.
I tried to run paracusia on Raspberry Pi, but realized the official Elixir package is 1.6 from erlang-solution.
I know it may be late to ask, but is it possible for paracusia to support Elixir 1.6 ?

**Comment by nroi** [comment]
> I know it may be late to ask, […]

Not at all, I just recently increased the version from 1.6 to 1.7 without giving it much thought. There aren't any features of Elixir 1.7 that are currently required by paracusia, so I think it's best to support Elixir 1.6 until debian-based distros support Elixir 1.7.

I've published a new version (0.2.8) which supports Elixir 1.6.

**Comment by yjchen** [comment]
Thanks. It works now.
