### ISSUE TITLE
Custom JSON Encoding for PlayerState

### ISSUE THREAD

**Issue by ghost** [nroi/paracusia#6]
I use Phoenix to pass messages from paracusia in backend to vue in frontend. There are a few custom types in paracusia which cannot be encoded in JSON. Would it be possible to add something like '@derive Jason.Encoder' in from of 'defstruct' so that they can be encoded in JSON format ?

The custom type I found are:
PlayerState
PlayerState.Status
MpdClient.AudioOutputs
PlayerState.Stats

**Comment by nroi** [comment]
I've just committed to the master branch. I'm going to release it to hex.pm in the next few days if everything works as desired.

**Comment by nroi** [comment]
Released on version 0.2.9.
