### ISSUE TITLE
Check file type before assuming it's a socket

### ISSUE THREAD

**Issue by mroach** [nroi/paracusia#9]
`ip_addresses/1` of `MpdClient` uses `File.exists?` to check if the hostname exists as a file. If so, classifies the host as a local socket.

In my case I'm running mpd in a docker container named `mpd` (via docker-compose) and my project happens to have a directory named `mpd`. So with `MPD_HOST=mpd`, `File.exists?("mpd")` returns true.

A more reliable way to check if it's a socket would be with: `File.stat` which will report the type as `:other` for a socket.

```elixir
{:ok, %{type: :other}} = File.stat("/var/run/docker.sock")
```

**Comment by nroi** [comment]
Feel free to send a PR with the fix you suggested. Otherwise, I'll fix it and push a new release to hex.pm soon.

**Comment by mroach** [comment]
I'll attempt to fix it tonight then! I was also thinking for future debugging of connectivity issues it would be nice to include the host, port, and protocol (inet, inet6, local) in the error messages. Any objection? I can do that while I'm in there.

**Comment by nroi** [comment]
Sure, go ahead.
